name = "CESTNumSim"
uuid = "e70600ac-6660-4470-bd65-b4bfe1a2c5a4"
authors = ["Mara Quach <maraquach@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
